
export const stockData = [
    // US Stocks (Major)
    { name: "Apple Inc.", ticker: "AAPL", sector: "Technology", logoUrl: "https://logo.clearbit.com/apple.com" },
    { name: "Microsoft Corporation", ticker: "MSFT", sector: "Technology", logoUrl: "https://logo.clearbit.com/microsoft.com" },
    { name: "Amazon.com, Inc.", ticker: "AMZN", sector: "Consumer Cyclical", logoUrl: "https://logo.clearbit.com/amazon.com" },
    { name: "NVIDIA Corporation", ticker: "NVDA", sector: "Technology", logoUrl: "https://logo.clearbit.com/nvidia.com" },
    { name: "Alphabet Inc. (Google)", ticker: "GOOGL", sector: "Communication Services", logoUrl: "https://logo.clearbit.com/google.com" },
    { name: "Tesla, Inc.", ticker: "TSLA", sector: "Consumer Cyclical", logoUrl: "https://logo.clearbit.com/tesla.com" },
    { name: "Meta Platforms, Inc.", ticker: "META", sector: "Communication Services", logoUrl: "https://logo.clearbit.com/meta.com" },
    { name: "Berkshire Hathaway Inc.", ticker: "BRK-B", sector: "Financial Services", logoUrl: "https://logo.clearbit.com/berkshirehathaway.com" },
    { name: "Eli Lilly and Company", ticker: "LLY", sector: "Healthcare", logoUrl: "https://logo.clearbit.com/lilly.com" },
    { name: "Broadcom Inc.", ticker: "AVGO", sector: "Technology", logoUrl: "https://logo.clearbit.com/broadcom.com" },
    { name: "JPMorgan Chase & Co.", ticker: "JPM", sector: "Financial Services", logoUrl: "https://logo.clearbit.com/jpmorganchase.com" },
    { name: "Visa Inc.", ticker: "V", sector: "Financial Services", logoUrl: "https://logo.clearbit.com/visa.com" },
    { name: "Exxon Mobil Corporation", ticker: "XOM", sector: "Energy", logoUrl: "https://logo.clearbit.com/exxonmobil.com" },
    { name: "UnitedHealth Group Inc.", ticker: "UNH", sector: "Healthcare", logoUrl: "https://logo.clearbit.com/uhg.com" },
    { name: "Mastercard Incorporated", ticker: "MA", sector: "Financial Services", logoUrl: "https://logo.clearbit.com/mastercard.com" },
    { name: "Johnson & Johnson", ticker: "JNJ", sector: "Healthcare", logoUrl: "https://logo.clearbit.com/jnj.com" },
    { name: "Procter & Gamble Company", ticker: "PG", sector: "Consumer Defensive", logoUrl: "https://logo.clearbit.com/pg.com" },
    { name: "Costco Wholesale Corporation", ticker: "COST", sector: "Consumer Defensive", logoUrl: "https://logo.clearbit.com/costco.com" },
    { name: "Home Depot, Inc.", ticker: "HD", sector: "Consumer Cyclical", logoUrl: "https://logo.clearbit.com/homedepot.com" },
    { name: "Merck & Co., Inc.", ticker: "MRK", sector: "Healthcare", logoUrl: "https://logo.clearbit.com/merck.com" },
    { name: "AbbVie Inc.", ticker: "ABBV", sector: "Healthcare", logoUrl: "https://logo.clearbit.com/abbvie.com" },
    { name: "Chevron Corporation", ticker: "CVX", sector: "Energy", logoUrl: "https://logo.clearbit.com/chevron.com" },
    { name: "Netflix, Inc.", ticker: "NFLX", sector: "Communication Services", logoUrl: "https://logo.clearbit.com/netflix.com" },
    { name: "Adobe Inc.", ticker: "ADBE", sector: "Technology", logoUrl: "https://logo.clearbit.com/adobe.com" },
    { name: "Salesforce, Inc.", ticker: "CRM", sector: "Technology", logoUrl: "https://logo.clearbit.com/salesforce.com" },
    { name: "Walmart Inc.", ticker: "WMT", sector: "Consumer Defensive", logoUrl: "https://logo.clearbit.com/walmart.com" },
    { name: "Bank of America Corp.", ticker: "BAC", sector: "Financial Services", logoUrl: "https://logo.clearbit.com/bankofamerica.com" },
    { name: "Coca-Cola Company", ticker: "KO", sector: "Consumer Defensive", logoUrl: "https://logo.clearbit.com/coca-colacompany.com" },
    { name: "PepsiCo, Inc.", ticker: "PEP", sector: "Consumer Defensive", logoUrl: "https://logo.clearbit.com/pepsico.com" },
    { name: "Oracle Corporation", ticker: "ORCL", sector: "Technology", logoUrl: "https://logo.clearbit.com/oracle.com" },
    { name: "Intel Corporation", ticker: "INTC", sector: "Technology", logoUrl: "https://logo.clearbit.com/intel.com" },
    { name: "Cisco Systems, Inc.", ticker: "CSCO", sector: "Technology", logoUrl: "https://logo.clearbit.com/cisco.com" },
    { name: "McDonald's Corporation", ticker: "MCD", sector: "Consumer Cyclical", logoUrl: "https://logo.clearbit.com/mcdonalds.com" },
    { name: "Walt Disney Company", ticker: "DIS", sector: "Communication Services", logoUrl: "https://logo.clearbit.com/thewaltdisneycompany.com" },
    { name: "Pfizer Inc.", ticker: "PFE", sector: "Healthcare", logoUrl: "https://logo.clearbit.com/pfizer.com" },
    { name: "AT&T Inc.", ticker: "T", sector: "Communication Services", logoUrl: "https://logo.clearbit.com/att.com" },
    { name: "Verizon Communications Inc.", ticker: "VZ", sector: "Communication Services", logoUrl: "https://logo.clearbit.com/verizon.com" },
    { name: "Starbucks Corporation", ticker: "SBUX", sector: "Consumer Cyclical", logoUrl: "https://logo.clearbit.com/starbucks.com" },
    { name: "Ford Motor Company", ticker: "F", sector: "Consumer Cyclical", logoUrl: "https://logo.clearbit.com/ford.com" },
    { name: "General Motors Company", ticker: "GM", sector: "Consumer Cyclical", logoUrl: "https://logo.clearbit.com/gm.com" },

    // Indian Stocks (Major from NSE)
    { name: "Reliance Industries Limited", ticker: "RELIANCE.NS", sector: "Conglomerate", logoUrl: "https://logo.clearbit.com/ril.com" },
    { name: "Tata Consultancy Services", ticker: "TCS.NS", sector: "Technology", logoUrl: "https://logo.clearbit.com/tcs.com" },
    { name: "HDFC Bank Limited", ticker: "HDFCBANK.NS", sector: "Financial Services", logoUrl: "https://logo.clearbit.com/hdfcbank.com" },
    { name: "ICICI Bank Limited", ticker: "ICICIBANK.NS", sector: "Financial Services", logoUrl: "https://logo.clearbit.com/icicibank.com" },
    { name: "Infosys Limited", ticker: "INFY.NS", sector: "Technology", logoUrl: "https://logo.clearbit.com/infosys.com" },
    { name: "Hindustan Unilever Limited", ticker: "HINDUNILVR.NS", sector: "Consumer Defensive", logoUrl: "https://logo.clearbit.com/hll.com" },
    { name: "State Bank of India", ticker: "SBIN.NS", sector: "Financial Services", logoUrl: "https://logo.clearbit.com/sbi.co.in" },
    { name: "Bharti Airtel Limited", ticker: "BHARTIARTL.NS", sector: "Communication Services", logoUrl: "https://logo.clearbit.com/airtel.com" },
    { name: "ITC Limited", ticker: "ITC.NS", sector: "Conglomerate", logoUrl: "https://logo.clearbit.com/itcportal.com" },
    { name: "Life Insurance Corporation of India", ticker: "LICI.NS", sector: "Financial Services", logoUrl: "https://logo.clearbit.com/licindia.in" },
    { name: "Bajaj Finance Limited", ticker: "BAJFINANCE.NS", sector: "Financial Services", logoUrl: "https://logo.clearbit.com/bajajfinserv.in" },
    { name: "Larsen & Toubro Limited", ticker: "LT.NS", sector: "Industrials", logoUrl: "https://logo.clearbit.com/larsentoubro.com" },
    { name: "Adani Enterprises Limited", ticker: "ADANIENT.NS", sector: "Conglomerate", logoUrl: "https://logo.clearbit.com/adani.com" },
    { name: "Kotak Mahindra Bank Limited", ticker: "KOTAKBANK.NS", sector: "Financial Services", logoUrl: "https://logo.clearbit.com/kotak.com" },
    { name: "HCL Technologies Limited", ticker: "HCLTECH.NS", sector: "Technology", logoUrl: "https://logo.clearbit.com/hcltech.com" },
    { name: "Maruti Suzuki India Limited", ticker: "MARUTI.NS", sector: "Consumer Cyclical", logoUrl: "https://logo.clearbit.com/marutisuzuki.com" },
    { name: "Sun Pharmaceutical Industries", ticker: "SUNPHARMA.NS", sector: "Healthcare", logoUrl: "https://logo.clearbit.com/sunpharma.com" },
    { name: "Tata Motors Limited", ticker: "TATAMOTORS.NS", sector: "Consumer Cyclical", logoUrl: "https://logo.clearbit.com/tatamotors.com" },
    { name: "Axis Bank Limited", ticker: "AXISBANK.NS", sector: "Financial Services", logoUrl: "https://logo.clearbit.com/axisbank.com" },
    { name: "Wipro Limited", ticker: "WIPRO.NS", sector: "Technology", logoUrl: "https://logo.clearbit.com/wipro.com" },
    { name: "NTPC Limited", ticker: "NTPC.NS", sector: "Utilities", logoUrl: "https://logo.clearbit.com/ntpc.co.in" },
    { name: "Adani Green Energy Limited", ticker: "ADANIGREEN.NS", sector: "Utilities", logoUrl: "https://logo.clearbit.com/adanigreenenergy.com" },
    { name: "Power Grid Corporation of India", ticker: "POWERGRID.NS", sector: "Utilities", logoUrl: "https://logo.clearbit.com/powergrid.in" },
    { name: "UltraTech Cement Limited", ticker: "ULTRACEMCO.NS", sector: "Basic Materials", logoUrl: "https://logo.clearbit.com/ultratechcement.com" },
    { name: "Asian Paints Limited", ticker: "ASIANPAINT.NS", sector: "Basic Materials", logoUrl: "https://logo.clearbit.com/asianpaints.com" },
    { name: "Tata Steel Limited", ticker: "TATASTEEL.NS", sector: "Basic Materials", logoUrl: "https://logo.clearbit.com/tatasteel.com" },
    { name: "Mahindra & Mahindra Limited", ticker: "M&M.NS", sector: "Consumer Cyclical", logoUrl: "https://logo.clearbit.com/mahindra.com" },
    { name: "JSW Steel Limited", ticker: "JSWSTEEL.NS", sector: "Basic Materials", logoUrl: "https://logo.clearbit.com/jsw.in" },
    { name: "Coal India Limited", ticker: "COALINDIA.NS", sector: "Energy", logoUrl: "https://logo.clearbit.com/coalindia.in" },
    { name: "Oil & Natural Gas Corporation", ticker: "ONGC.NS", sector: "Energy", logoUrl: "https://logo.clearbit.com/ongcindia.com" }
];
