
export const stockData = [
    { name: "Apple Inc.", ticker: "AAPL", sector: "Technology" },
    { name: "Microsoft Corporation", ticker: "MSFT", sector: "Technology" },
    { name: "Amazon.com, Inc.", ticker: "AMZN", sector: "Consumer Cyclical" },
    { name: "NVIDIA Corporation", ticker: "NVDA", sector: "Technology" },
    { name: "Alphabet Inc.", ticker: "GOOGL", sector: "Communication Services" },
    { name: "Tesla, Inc.", ticker: "TSLA", sector: "Consumer Cyclical" },
    { name: "Meta Platforms, Inc.", ticker: "META", sector: "Communication Services" },
    { name: "Berkshire Hathaway Inc.", ticker: "BRK.B", sector: "Financial Services" },
    { name: "Eli Lilly and Company", ticker: "LLY", sector: "Healthcare" },
    { name: "Broadcom Inc.", ticker: "AVGO", sector: "Technology" },
    { name: "JPMorgan Chase & Co.", ticker: "JPM", sector: "Financial Services" },
    { name: "Visa Inc.", ticker: "V", sector: "Financial Services" },
    { name: "Exxon Mobil Corporation", ticker: "XOM", sector: "Energy" },
    { name: "UnitedHealth Group Incorporated", ticker: "UNH", sector: "Healthcare" },
    { name: "Mastercard Incorporated", ticker: "MA", sector: "Financial Services" },
    { name: "Johnson & Johnson", ticker: "JNJ", sector: "Healthcare" },
    { name: "Procter & Gamble Company", ticker: "PG", sector: "Consumer Defensive" },
    { name: "Costco Wholesale Corporation", ticker: "COST", sector: "Consumer Defensive" },
    { name: "Home Depot, Inc.", ticker: "HD", sector: "Consumer Cyclical" },
    { name: "Merck & Co., Inc.", ticker: "MRK", sector: "Healthcare" },
    { name: "AbbVie Inc.", ticker: "ABBV", sector: "Healthcare" },
    { name: "Chevron Corporation", ticker: "CVX", sector: "Energy" },
    { name: "Netflix, Inc.", ticker: "NFLX", sector: "Communication Services" },
    { name: "Adobe Inc.", ticker: "ADBE", sector: "Technology" },
    { name: "Salesforce, Inc.", ticker: "CRM", sector: "Technology" },
    { name: "Walmart Inc.", ticker: "WMT", sector: "Consumer Defensive" },
    { name: "Bank of America Corporation", ticker: "BAC", sector: "Financial Services" },
    { name: "Reliance Industries Limited", ticker: "RELIANCE.NS", sector: "Conglomerate" },
    { name: "Tata Consultancy Services Limited", ticker: "TCS.NS", sector: "Technology" },
    { name: "HDFC Bank Limited", ticker: "HDFCBANK.NS", sector: "Financial Services" },
    { name: "Infosys Limited", ticker: "INFY.NS", sector: "Technology" },
    { name: "ICICI Bank Limited", ticker: "ICICIBANK.NS", sector: "Financial Services" },
    { name: "Hindustan Unilever Limited", ticker: "HINDUNILVR.NS", sector: "Consumer Defensive" },
    { name: "State Bank of India", ticker: "SBIN.NS", sector: "Financial Services" },
    { name: "Bharti Airtel Limited", ticker: "BHARTIARTL.NS", sector: "Communication Services" },
    { name: "ITC Limited", ticker: "ITC.NS", sector: "Conglomerate" },
    { name: "Bajaj Finance Limited", ticker: "BAJFINANCE.NS", sector: "Financial Services" },
];
