
export const stockData = [
    { name: "Apple Inc.", ticker: "AAPL" },
    { name: "Microsoft Corporation", ticker: "MSFT" },
    { name: "Amazon.com, Inc.", ticker: "AMZN" },
    { name: "NVIDIA Corporation", ticker: "NVDA" },
    { name: "Alphabet Inc.", ticker: "GOOGL" },
    { name: "Tesla, Inc.", ticker: "TSLA" },
    { name: "Meta Platforms, Inc.", ticker: "META" },
    { name: "Berkshire Hathaway Inc.", ticker: "BRK.B" },
    { name: "Eli Lilly and Company", ticker: "LLY" },
    { name: "Broadcom Inc.", ticker: "AVGO" },
    { name: "JPMorgan Chase & Co.", ticker: "JPM" },
    { name: "Visa Inc.", ticker: "V" },
    { name: "Exxon Mobil Corporation", ticker: "XOM" },
    { name: "UnitedHealth Group Incorporated", ticker: "UNH" },
    { name: "Mastercard Incorporated", ticker: "MA" },
    { name: "Johnson & Johnson", ticker: "JNJ" },
    { name: "Procter & Gamble Company", ticker: "PG" },
    { name: "Costco Wholesale Corporation", ticker: "COST" },
    { name: "Home Depot, Inc.", ticker: "HD" },
    { name: "Merck & Co., Inc.", ticker: "MRK" },
    { name: "AbbVie Inc.", ticker: "ABBV" },
    { name: "Chevron Corporation", ticker: "CVX" },
    { name: "Netflix, Inc.", ticker: "NFLX" },
    { name: "Adobe Inc.", ticker: "ADBE" },
    { name: "Salesforce, Inc.", ticker: "CRM" },
    { name: "Walmart Inc.", ticker: "WMT" },
    { name: "Bank of America Corporation", ticker: "BAC" },
    { name: "Reliance Industries Limited", ticker: "RELIANCE.NS" },
    { name: "Tata Consultancy Services Limited", ticker: "TCS.NS" },
    { name: "HDFC Bank Limited", ticker: "HDFCBANK.NS" },
    { name: "Infosys Limited", ticker: "INFY.NS" },
    { name: "ICICI Bank Limited", ticker: "ICICIBANK.NS" },
    { name: "Hindustan Unilever Limited", ticker: "HINDUNILVR.NS" },
    { name: "State Bank of India", ticker: "SBIN.NS" },
    { name: "Bharti Airtel Limited", ticker: "BHARTIARTL.NS" },
    { name: "ITC Limited", ticker: "ITC.NS" },
    { name: "Bajaj Finance Limited", ticker: "BAJFINANCE.NS" },
];
